; --- NOTE ---
; This (data) sprite file was AUTO GENERATED by frame_delta
; TITLE02.BIN TITLE04.BIN 2 -data
;
; === Aux ===
        db $40              ; Base Address
        db   3              ; Spans @ $40xx
            db $08, $58
            db $30, $AF
            db $00, $EF
        db   6              ; Spans @ $41xx
            db $08, $47
            db $00, $6F
            db $08, $AF
            db $00, $C7
            db $04, $D7
            db $00, $EF
        db   2              ; Spans @ $42xx
            db $60, $57
            db $00, $AF
        db   4              ; Spans @ $43xx
            db $00, $2F
            db $20, $47
            db $20, $6F
            db $08, $C7
        db   5              ; Spans @ $44xx
            db $03, $2F
            db $08, $58
            db $00, $AF
            db $0C, $C8
            db $00, $EF
        db   5              ; Spans @ $45xx
            db $08, $47
            db $00, $6F
            db $08, $AF
            db $00, $C7
            db $08, $D7
        db   2              ; Spans @ $46xx
            db $60, $57
            db $00, $AF
        db   4              ; Spans @ $47xx
            db $00, $2F
            db $20, $47
            db $60, $6F
            db $08, $C7
        db   4              ; Spans @ $48xx
            db $01, $2F
            db $00, $AF
            db $08, $C8
            db $00, $EF
        db   5              ; Spans @ $49xx
            db $20, $47
            db $00, $6F
            db $08, $AF
            db $00, $C7
            db $08, $D8
        db   2              ; Spans @ $4Axx
            db $40, $57
            db $00, $AF
        db   3              ; Spans @ $4Bxx
            db $20, $47
            db $60, $6F
            db $08, $C7
        db   4              ; Spans @ $4Cxx
            db $03, $2E
            db $00, $AF
            db $08, $C8
            db $00, $EF
        db   5              ; Spans @ $4Dxx
            db $00, $47
            db $00, $6F
            db $08, $AF
            db $00, $C7
            db $08, $D7
        db   3              ; Spans @ $4Exx
            db $08, $58
            db $00, $AF
            db $20, $C7
        db   2              ; Spans @ $4Fxx
            db $20, $47
            db $08, $C7
        db   5              ; Spans @ $50xx
            db $03, $2F
            db $00, $AF
            db $08, $C8
            db $08, $D8
            db $00, $EF
        db   5              ; Spans @ $51xx
            db $00, $47
            db $00, $6F
            db $08, $AF
            db $00, $C7
            db $20, $D7
        db   3              ; Spans @ $52xx
            db $00, $AF
            db $20, $C7
            db $20, $EF
        db   2              ; Spans @ $53xx
            db $08, $47
            db $08, $B0
        db   4              ; Spans @ $54xx
            db $01, $2F
            db $08, $C7
            db $08, $D8
            db $00, $EF
        db   6              ; Spans @ $55xx
            db $08, $30
            db $00, $47
            db $00, $6F
            db $08, $AF
            db $00, $C7
            db $60, $D7
        db   4              ; Spans @ $56xx
            db $00, $AF
            db $20, $C7
            db $00, $D8
            db $20, $EF
        db   2              ; Spans @ $57xx
            db $08, $47
            db $08, $B0
        db   5              ; Spans @ $58xx
            db $13, $2F
            db $00, $6F
            db $08, $C7
            db $09, $D8
            db $00, $EF
        db   7              ; Spans @ $59xx
            db $08, $2F
            db $00, $47
            db $20, $57
            db $00, $6F
            db $08, $AF
            db $00, $C7
            db $60, $D7
        db   4              ; Spans @ $5Axx
            db $00, $AF
            db $20, $C7
            db $00, $D8
            db $20, $EF
        db   2              ; Spans @ $5Bxx
            db $08, $47
            db $08, $B0
        db   3              ; Spans @ $5Cxx
            db $00, $6F
            db $60, $C7
            db $00, $EF
        db   6              ; Spans @ $5Dxx
            db $08, $2F
            db $00, $47
            db $60, $57
            db $00, $6F
            db $20, $AF
            db $60, $D7
        db   5              ; Spans @ $5Exx
            db $00, $30
            db $00, $AF
            db $20, $C7
            db $00, $D8
            db $20, $EF
        db   2              ; Spans @ $5Fxx
            db $09, $47
            db $08, $B0
; === Main ===
        db   4 + $80        ; Spans @ $40xx
            db $7E, $57
            db $02, $AE
            db $00, $C8
            db $00, $EF
        db   7              ; Spans @ $41xx
            db $04, $2F
            db $4E, $47
            db $00, $6F
            db $44, $AF
            db $00, $C7
            db $6F, $D7
            db $54, $EF
        db   4              ; Spans @ $42xx
            db $44, $2F
            db $47, $57
            db $00, $AF
            db $04, $C7
        db   4              ; Spans @ $43xx
            db $00, $2F
            db $44, $47
            db $4C, $6F
            db $5F, $C7
        db   6              ; Spans @ $44xx
            db $08, $2E
            db $6E, $57
            db $00, $6F
            db $02, $AF
            db $00, $C8
            db $00, $EF
        db   6              ; Spans @ $45xx
            db $44, $2F
            db $4E, $47
            db $00, $6F
            db $44, $AF
            db $00, $C7
            db $44, $D7
        db   4              ; Spans @ $46xx
            db $00, $2F
            db $4D, $57
            db $00, $AF
            db $04, $C7
        db   5              ; Spans @ $47xx
            db $00, $2F
            db $44, $47
            db $4C, $6F
            db $40, $AF
            db $4E, $C7
        db   6              ; Spans @ $48xx
            db $18, $2E
            db $44, $57
            db $00, $6F
            db $00, $AF
            db $00, $C8
            db $00, $EF
        db   6              ; Spans @ $49xx
            db $44, $2F
            db $5E, $47
            db $00, $6F
            db $44, $AF
            db $00, $C7
            db $42, $D7
        db   4              ; Spans @ $4Axx
            db $00, $2F
            db $4C, $57
            db $00, $AF
            db $04, $C7
        db   5              ; Spans @ $4Bxx
            db $00, $2F
            db $4C, $47
            db $44, $6F
            db $40, $AF
            db $4C, $C7
        db   5              ; Spans @ $4Cxx
            db $18, $2E
            db $00, $6F
            db $00, $AF
            db $44, $C7
            db $00, $EF
        db   6              ; Spans @ $4Dxx
            db $44, $2F
            db $40, $57
            db $00, $6F
            db $44, $AF
            db $00, $C7
            db $44, $D7
        db   4              ; Spans @ $4Exx
            db $00, $2F
            db $00, $AF
            db $04, $C7
            db $04, $EF
        db   3              ; Spans @ $4Fxx
            db $4C, $47
            db $40, $AF
            db $44, $C7
        db   6              ; Spans @ $50xx
            db $18, $2E
            db $00, $6F
            db $00, $AF
            db $44, $C7
            db $58, $D7
            db $00, $EF
        db   7              ; Spans @ $51xx
            db $44, $2F
            db $00, $47
            db $44, $57
            db $00, $6F
            db $4D, $AF
            db $00, $C7
            db $44, $D7
        db   5              ; Spans @ $52xx
            db $00, $2F
            db $44, $57
            db $00, $AF
            db $04, $C7
            db $04, $EF
        db   3              ; Spans @ $53xx
            db $4C, $47
            db $40, $AF
            db $44, $C7
        db   5              ; Spans @ $54xx
            db $00, $2E
            db $00, $6F
            db $44, $C7
            db $4C, $D7
            db $00, $EF
        db   7              ; Spans @ $55xx
            db $44, $2F
            db $00, $47
            db $44, $57
            db $40, $6F
            db $4E, $AF
            db $00, $C7
            db $44, $D7
        db   6              ; Spans @ $56xx
            db $00, $2F
            db $40, $57
            db $00, $AF
            db $04, $C7
            db $00, $D7
            db $04, $EF
        db   2              ; Spans @ $57xx
            db $4C, $47
            db $40, $AF
        db   7              ; Spans @ $58xx
            db $00, $2E
            db $01, $48
            db $00, $6F
            db $04, $AF
            db $44, $C7
            db $68, $D7
            db $00, $EF
        db   7              ; Spans @ $59xx
            db $44, $2F
            db $00, $47
            db $44, $57
            db $50, $6F
            db $4C, $AF
            db $00, $C7
            db $46, $D7
        db   6              ; Spans @ $5Axx
            db $00, $2F
            db $04, $47
            db $00, $AF
            db $44, $C7
            db $00, $D7
            db $04, $EF
        db   2              ; Spans @ $5Bxx
            db $4E, $47
            db $44, $AF
        db   6              ; Spans @ $5Cxx
            db $00, $2E
            db $01, $48
            db $00, $6F
            db $04, $AF
            db $4C, $C7
            db $00, $EF
        db   6              ; Spans @ $5Dxx
            db $44, $2F
            db $00, $47
            db $46, $57
            db $50, $6F
            db $44, $AF
            db $00, $C7
        db   6              ; Spans @ $5Exx
            db $00, $2F
            db $04, $47
            db $00, $AF
            db $44, $C7
            db $00, $D7
            db $4C, $EF
        db   2              ; Spans @ $5Fxx
            db $4F, $47
            db $44, $AF
        db 0
; Total Bytes Aux.: $0118 (280)
; Total Bytes Main: $0164 (356)
; Total Bytes Misc: $0002 (2)
;================== $027E (638)
