; --- NOTE ---
; This (data) sprite file was AUTO GENERATED by frame_delta
; TITLE04.BIN TITLE02.BIN 2 -data
;
; === Aux ===
        db $40              ; Base Address
        db   3              ; Spans @ $40xx
            db $00, $58
            db $22, $AF
            db $20, $EF
        db   6              ; Spans @ $41xx
            db $00, $47
            db $08, $6F
            db $00, $AF
            db $08, $C7
            db $00, $D7
            db $60, $EF
        db   2              ; Spans @ $42xx
            db $00, $57
            db $08, $AF
        db   4              ; Spans @ $43xx
            db $08, $2F
            db $00, $47
            db $00, $6F
            db $00, $C7
        db   5              ; Spans @ $44xx
            db $23, $2F
            db $00, $58
            db $26, $AF
            db $5C, $C8
            db $20, $EF
        db   5              ; Spans @ $45xx
            db $00, $47
            db $08, $6F
            db $00, $AF
            db $08, $C7
            db $00, $D7
        db   2              ; Spans @ $46xx
            db $00, $57
            db $08, $AF
        db   4              ; Spans @ $47xx
            db $20, $2F
            db $00, $47
            db $00, $6F
            db $00, $C7
        db   4              ; Spans @ $48xx
            db $21, $2F
            db $66, $AF
            db $00, $C8
            db $20, $EF
        db   5              ; Spans @ $49xx
            db $00, $47
            db $62, $6F
            db $00, $AF
            db $08, $C7
            db $00, $D8
        db   2              ; Spans @ $4Axx
            db $00, $57
            db $08, $AF
        db   3              ; Spans @ $4Bxx
            db $00, $47
            db $00, $6F
            db $00, $C7
        db   4              ; Spans @ $4Cxx
            db $23, $2E
            db $70, $AF
            db $00, $C8
            db $20, $EF
        db   5              ; Spans @ $4Dxx
            db $20, $47
            db $62, $6F
            db $00, $AF
            db $62, $C7
            db $00, $D7
        db   3              ; Spans @ $4Exx
            db $00, $58
            db $08, $AF
            db $00, $C7
        db   2              ; Spans @ $4Fxx
            db $00, $47
            db $00, $C7
        db   5              ; Spans @ $50xx
            db $23, $2F
            db $20, $AF
            db $00, $C8
            db $00, $D8
            db $20, $EF
        db   5              ; Spans @ $51xx
            db $20, $47
            db $62, $6F
            db $00, $AF
            db $08, $C7
            db $00, $D7
        db   3              ; Spans @ $52xx
            db $08, $AF
            db $00, $C7
            db $00, $EF
        db   2              ; Spans @ $53xx
            db $00, $47
            db $00, $B0
        db   4              ; Spans @ $54xx
            db $21, $2F
            db $00, $C7
            db $00, $D8
            db $20, $EF
        db   6              ; Spans @ $55xx
            db $00, $30
            db $20, $47
            db $74, $6F
            db $00, $AF
            db $08, $C7
            db $00, $D7
        db   4              ; Spans @ $56xx
            db $08, $AF
            db $00, $C7
            db $08, $D8
            db $00, $EF
        db   2              ; Spans @ $57xx
            db $00, $47
            db $00, $B0
        db   5              ; Spans @ $58xx
            db $53, $2F
            db $20, $6F
            db $00, $C7
            db $00, $D8
            db $20, $EF
        db   7              ; Spans @ $59xx
            db $00, $2F
            db $08, $47
            db $00, $57
            db $74, $6F
            db $00, $AF
            db $20, $C7
            db $00, $D7
        db   4              ; Spans @ $5Axx
            db $08, $AF
            db $00, $C7
            db $08, $D8
            db $00, $EF
        db   2              ; Spans @ $5Bxx
            db $00, $47
            db $00, $B0
        db   3              ; Spans @ $5Cxx
            db $20, $6F
            db $00, $C7
            db $08, $EF
        db   6              ; Spans @ $5Dxx
            db $00, $2F
            db $08, $47
            db $00, $57
            db $60, $6F
            db $00, $AF
            db $00, $D7
        db   5              ; Spans @ $5Exx
            db $08, $30
            db $08, $AF
            db $00, $C7
            db $09, $D8
            db $00, $EF
        db   2              ; Spans @ $5Fxx
            db $00, $47
            db $00, $B0
; === Main ===
        db   4 + $80        ; Spans @ $40xx
            db $00, $57
            db $44, $AE
            db $13, $C8
            db $04, $EF
        db   7              ; Spans @ $41xx
            db $00, $2F
            db $40, $47
            db $4C, $6F
            db $00, $AF
            db $4C, $C7
            db $00, $D7
            db $4E, $EF
        db   4              ; Spans @ $42xx
            db $04, $2F
            db $44, $57
            db $44, $AF
            db $00, $C7
        db   4              ; Spans @ $43xx
            db $4C, $2F
            db $00, $47
            db $00, $6F
            db $00, $C7
        db   6              ; Spans @ $44xx
            db $09, $2E
            db $00, $57
            db $04, $6F
            db $44, $AF
            db $01, $C8
            db $44, $EF
        db   6              ; Spans @ $45xx
            db $00, $2F
            db $40, $47
            db $4E, $6F
            db $00, $AF
            db $4C, $C7
            db $00, $D7
        db   4              ; Spans @ $46xx
            db $04, $2F
            db $7E, $57
            db $44, $AF
            db $00, $C7
        db   5              ; Spans @ $47xx
            db $44, $2F
            db $00, $47
            db $00, $6F
            db $00, $AF
            db $00, $C7
        db   6              ; Spans @ $48xx
            db $19, $2E
            db $00, $57
            db $04, $6F
            db $44, $AF
            db $01, $C8
            db $44, $EF
        db   6              ; Spans @ $49xx
            db $00, $2F
            db $44, $47
            db $4C, $6F
            db $00, $AF
            db $4C, $C7
            db $40, $D7
        db   4              ; Spans @ $4Axx
            db $04, $2F
            db $6E, $57
            db $44, $AF
            db $00, $C7
        db   5              ; Spans @ $4Bxx
            db $44, $2F
            db $00, $47
            db $00, $6F
            db $00, $AF
            db $00, $C7
        db   5              ; Spans @ $4Cxx
            db $19, $2E
            db $04, $6F
            db $04, $AF
            db $64, $C7
            db $44, $EF
        db   6              ; Spans @ $4Dxx
            db $00, $2F
            db $00, $57
            db $4C, $6F
            db $00, $AF
            db $4C, $C7
            db $40, $D7
        db   4              ; Spans @ $4Exx
            db $44, $2F
            db $44, $AF
            db $00, $C7
            db $00, $EF
        db   3              ; Spans @ $4Fxx
            db $00, $47
            db $00, $AF
            db $00, $C7
        db   6              ; Spans @ $50xx
            db $19, $2E
            db $04, $6F
            db $04, $AF
            db $00, $C7
            db $00, $D7
            db $44, $EF
        db   7              ; Spans @ $51xx
            db $00, $2F
            db $44, $47
            db $00, $57
            db $4C, $6F
            db $00, $AF
            db $4E, $C7
            db $40, $D7
        db   5              ; Spans @ $52xx
            db $44, $2F
            db $00, $57
            db $44, $AF
            db $00, $C7
            db $00, $EF
        db   3              ; Spans @ $53xx
            db $00, $47
            db $00, $AF
            db $00, $C7
        db   5              ; Spans @ $54xx
            db $04, $2E
            db $04, $6F
            db $00, $C7
            db $00, $D7
            db $4C, $EF
        db   7              ; Spans @ $55xx
            db $00, $2F
            db $44, $47
            db $00, $57
            db $4C, $6F
            db $00, $AF
            db $4E, $C7
            db $40, $D7
        db   6              ; Spans @ $56xx
            db $44, $2F
            db $00, $57
            db $44, $AF
            db $00, $C7
            db $58, $D7
            db $00, $EF
        db   2              ; Spans @ $57xx
            db $00, $47
            db $00, $AF
        db   7              ; Spans @ $58xx
            db $04, $2E
            db $11, $48
            db $04, $6F
            db $00, $AF
            db $00, $C7
            db $00, $D7
            db $4C, $EF
        db   7              ; Spans @ $59xx
            db $00, $2F
            db $44, $47
            db $00, $57
            db $4E, $6F
            db $00, $AF
            db $5E, $C7
            db $40, $D7
        db   6              ; Spans @ $5Axx
            db $44, $2F
            db $00, $47
            db $4D, $AF
            db $00, $C7
            db $4C, $D7
            db $00, $EF
        db   2              ; Spans @ $5Bxx
            db $00, $47
            db $00, $AF
        db   6              ; Spans @ $5Cxx
            db $44, $2E
            db $11, $48
            db $04, $6F
            db $00, $AF
            db $00, $C7
            db $4C, $EF
        db   6              ; Spans @ $5Dxx
            db $00, $2F
            db $4C, $47
            db $00, $57
            db $56, $6F
            db $00, $AF
            db $44, $C7
        db   6              ; Spans @ $5Exx
            db $44, $2F
            db $00, $47
            db $4E, $AF
            db $00, $C7
            db $68, $D7
            db $00, $EF
        db   2              ; Spans @ $5Fxx
            db $00, $47
            db $00, $AF
        db 0
; Total Bytes Aux.: $0118 (280)
; Total Bytes Main: $0164 (356)
; Total Bytes Misc: $0002 (2)
;================== $027E (638)
