; --- NOTE ---
; This (data) sprite file was AUTO GENERATED by frame_delta
; TITLE01.BIN TITLE03.BIN 1 -data
;
; === Aux ===
        db $20              ; Base Address
        db   5              ; Spans @ $20xx
            db $00, $2E
            db $20, $57
            db $00, $6F
            db $26, $AF
            db $00, $EF
        db   3              ; Spans @ $21xx
            db $08, $2F
            db $00, $47
            db $00, $58
        db   4              ; Spans @ $22xx
            db $00, $2F
            db $20, $47
            db $08, $C7
            db $00, $D7
        db   5              ; Spans @ $23xx
            db $20, $2F
            db $00, $57
            db $60, $6F
            db $08, $AF
            db $00, $C7
        db   5              ; Spans @ $24xx
            db $00, $2E
            db $08, $57
            db $00, $6F
            db $36, $AF
            db $1C, $C8
        db   3              ; Spans @ $25xx
            db $08, $2F
            db $00, $47
            db $00, $58
        db   5              ; Spans @ $26xx
            db $00, $2F
            db $20, $47
            db $08, $C7
            db $00, $D7
            db $08, $EF
        db   3              ; Spans @ $27xx
            db $20, $2F
            db $00, $57
            db $00, $C7
        db   4              ; Spans @ $28xx
            db $00, $2E
            db $08, $57
            db $00, $6F
            db $22, $AF
        db   2              ; Spans @ $29xx
            db $08, $2F
            db $00, $47
        db   5              ; Spans @ $2Axx
            db $00, $2F
            db $20, $47
            db $08, $C7
            db $00, $D7
            db $08, $EF
        db   4              ; Spans @ $2Bxx
            db $08, $2F
            db $00, $57
            db $09, $AF
            db $00, $C7
        db   4              ; Spans @ $2Cxx
            db $00, $2E
            db $08, $57
            db $00, $6F
            db $26, $AF
        db   4              ; Spans @ $2Dxx
            db $08, $30
            db $00, $47
            db $00, $B0
            db $00, $D8
        db   5              ; Spans @ $2Exx
            db $00, $2F
            db $08, $47
            db $08, $C7
            db $00, $D7
            db $08, $EF
        db   2              ; Spans @ $2Fxx
            db $08, $2F
            db $00, $C7
        db   6              ; Spans @ $30xx
            db $00, $2E
            db $08, $57
            db $00, $6F
            db $08, $AF
            db $09, $C7
            db $00, $D8
        db   3              ; Spans @ $31xx
            db $00, $47
            db $00, $AF
            db $00, $D8
        db   4              ; Spans @ $32xx
            db $00, $2F
            db $08, $47
            db $00, $D8
            db $08, $EF
        db   2              ; Spans @ $33xx
            db $08, $2F
            db $00, $C7
        db   6              ; Spans @ $34xx
            db $00, $2E
            db $20, $57
            db $00, $6F
            db $08, $AF
            db $09, $C7
            db $00, $D8
        db   2              ; Spans @ $35xx
            db $00, $AF
            db $00, $D8
        db   5              ; Spans @ $36xx
            db $00, $2F
            db $08, $47
            db $00, $57
            db $00, $D7
            db $08, $EF
        db   3              ; Spans @ $37xx
            db $08, $2F
            db $00, $86
            db $00, $C7
        db   5              ; Spans @ $38xx
            db $12, $2F
            db $00, $6F
            db $08, $AF
            db $09, $C7
            db $00, $D8
        db   3              ; Spans @ $39xx
            db $00, $AF
            db $20, $C7
            db $00, $D8
        db   4              ; Spans @ $3Axx
            db $08, $47
            db $00, $57
            db $08, $D7
            db $08, $EF
        db   3              ; Spans @ $3Bxx
            db $08, $2F
            db $00, $86
            db $00, $C7
        db   3              ; Spans @ $3Cxx
            db $00, $6F
            db $08, $AF
            db $00, $D8
        db   3              ; Spans @ $3Dxx
            db $00, $AF
            db $20, $C7
            db $00, $D8
        db   4              ; Spans @ $3Exx
            db $08, $47
            db $00, $57
            db $00, $D7
            db $08, $EF
        db   4              ; Spans @ $3Fxx
            db $08, $2F
            db $00, $86
            db $20, $AF
            db $00, $C7
; === Main ===
        db   5 + $80        ; Spans @ $20xx
            db $44, $57
            db $00, $6F
            db $46, $AE
            db $13, $C8
            db $00, $EF
        db   3              ; Spans @ $21xx
            db $4C, $2F
            db $00, $57
            db $00, $AF
        db   4              ; Spans @ $22xx
            db $00, $2F
            db $44, $47
            db $4C, $C7
            db $00, $D7
        db   5              ; Spans @ $23xx
            db $44, $2F
            db $44, $57
            db $4E, $6F
            db $4E, $AF
            db $00, $C7
        db   7              ; Spans @ $24xx
            db $08, $2E
            db $44, $57
            db $00, $6F
            db $46, $AF
            db $11, $C8
            db $00, $D7
            db $00, $EF
        db   6              ; Spans @ $25xx
            db $4E, $2F
            db $00, $47
            db $00, $57
            db $00, $AF
            db $04, $C7
            db $00, $D7
        db   5              ; Spans @ $26xx
            db $00, $2F
            db $44, $47
            db $4E, $C7
            db $00, $D7
            db $44, $EF
        db   4              ; Spans @ $27xx
            db $44, $2F
            db $6C, $6F
            db $4E, $AF
            db $00, $C7
        db   6              ; Spans @ $28xx
            db $18, $2E
            db $4D, $57
            db $00, $6F
            db $44, $AF
            db $11, $C8
            db $00, $D7
        db   6              ; Spans @ $29xx
            db $4E, $2F
            db $00, $47
            db $00, $57
            db $00, $AF
            db $04, $C7
            db $00, $D7
        db   6              ; Spans @ $2Axx
            db $00, $2F
            db $4C, $47
            db $04, $AF
            db $4E, $C7
            db $00, $D7
            db $44, $EF
        db   5              ; Spans @ $2Bxx
            db $4C, $2F
            db $7E, $57
            db $04, $6F
            db $4E, $AF
            db $00, $C7
        db   6              ; Spans @ $2Cxx
            db $18, $2E
            db $4E, $57
            db $00, $6F
            db $44, $AF
            db $01, $C7
            db $00, $D7
        db   5              ; Spans @ $2Dxx
            db $4E, $2F
            db $00, $47
            db $00, $AF
            db $04, $C7
            db $00, $D7
        db   6              ; Spans @ $2Exx
            db $00, $2F
            db $4C, $47
            db $04, $AF
            db $5E, $C7
            db $40, $D7
            db $4C, $EF
        db   4              ; Spans @ $2Fxx
            db $4C, $2F
            db $00, $47
            db $44, $AF
            db $00, $C7
        db   6              ; Spans @ $30xx
            db $18, $2E
            db $4C, $57
            db $00, $6F
            db $44, $AF
            db $01, $C8
            db $00, $D7
        db   5              ; Spans @ $31xx
            db $44, $2F
            db $00, $47
            db $00, $AF
            db $04, $C7
            db $00, $D7
        db   7              ; Spans @ $32xx
            db $00, $2F
            db $4C, $47
            db $00, $57
            db $44, $AF
            db $44, $C7
            db $40, $D7
            db $4C, $EF
        db   3              ; Spans @ $33xx
            db $4C, $2F
            db $00, $47
            db $00, $C7
        db   6              ; Spans @ $34xx
            db $10, $2E
            db $44, $57
            db $00, $6F
            db $44, $AF
            db $01, $C7
            db $00, $D7
        db   5              ; Spans @ $35xx
            db $00, $2F
            db $00, $47
            db $00, $AF
            db $44, $C7
            db $00, $D7
        db   6              ; Spans @ $36xx
            db $00, $2F
            db $4C, $47
            db $00, $57
            db $44, $AF
            db $40, $D7
            db $4C, $EF
        db   3              ; Spans @ $37xx
            db $4C, $2F
            db $00, $47
            db $00, $C7
        db   7              ; Spans @ $38xx
            db $30, $2E
            db $11, $48
            db $44, $57
            db $00, $6F
            db $44, $AF
            db $01, $C7
            db $00, $D7
        db   4              ; Spans @ $39xx
            db $00, $2F
            db $00, $AF
            db $44, $C7
            db $00, $D7
        db   6              ; Spans @ $3Axx
            db $00, $2F
            db $4C, $47
            db $00, $57
            db $44, $AF
            db $40, $D7
            db $4C, $EF
        db   3              ; Spans @ $3Bxx
            db $4C, $2F
            db $00, $47
            db $00, $C7
        db   6              ; Spans @ $3Cxx
            db $04, $2E
            db $11, $48
            db $00, $6F
            db $44, $AF
            db $6E, $C7
            db $00, $D7
        db   4              ; Spans @ $3Dxx
            db $00, $2F
            db $00, $AF
            db $44, $C7
            db $00, $D7
        db   5              ; Spans @ $3Exx
            db $4C, $47
            db $00, $57
            db $44, $AF
            db $40, $D7
            db $4E, $EF
        db   5              ; Spans @ $3Fxx
            db $4C, $2F
            db $00, $47
            db $10, $86
            db $04, $AF
            db $00, $C7
        db 0
; Total Bytes Aux.: $0116 (278)
; Total Bytes Main: $0168 (360)
; Total Bytes Misc: $0002 (2)
;================== $0280 (640)
