; --- NOTE ---
; This (data) sprite file was AUTO GENERATED by frame_delta
; ../TITLELOGO.DHGR ../TITLE01.DHGR 1 -data
;
; === Aux ===
        db $20              ; Base Address
        db   2              ; Spans @ $20xx
            db $20, $6F
            db $08, $EF
        db   1              ; Spans @ $21xx
            db $08, $58
        db   2              ; Spans @ $22xx
            db $08, $2F
            db $08, $D7
        db   2              ; Spans @ $23xx
            db $08, $57
            db $20, $C7
        db   1              ; Spans @ $24xx
            db $08, $6F
        db   1              ; Spans @ $25xx
            db $08, $58
        db   2              ; Spans @ $26xx
            db $08, $2F
            db $08, $D7
        db   2              ; Spans @ $27xx
            db $08, $57
            db $20, $C7
        db   1              ; Spans @ $28xx
            db $08, $6F
        db   2              ; Spans @ $2Axx
            db $08, $2F
            db $08, $D7
        db   2              ; Spans @ $2Bxx
            db $08, $57
            db $20, $C7
        db   1              ; Spans @ $2Cxx
            db $08, $6F
        db   2              ; Spans @ $2Dxx
            db $08, $B0
            db $08, $D8
        db   2              ; Spans @ $2Exx
            db $08, $2F
            db $08, $D7
        db   1              ; Spans @ $2Fxx
            db $20, $C7
        db   2              ; Spans @ $30xx
            db $09, $6F
            db $08, $D8
        db   2              ; Spans @ $31xx
            db $08, $AF
            db $08, $D8
        db   2              ; Spans @ $32xx
            db $08, $2F
            db $08, $D8
        db   1              ; Spans @ $33xx
            db $20, $C7
        db   2              ; Spans @ $34xx
            db $08, $6F
            db $08, $D8
        db   2              ; Spans @ $35xx
            db $08, $AF
            db $08, $D8
        db   3              ; Spans @ $36xx
            db $20, $2F
            db $20, $57
            db $08, $D7
        db   1              ; Spans @ $37xx
            db $20, $C7
        db   2              ; Spans @ $38xx
            db $08, $6F
            db $08, $D8
        db   2              ; Spans @ $39xx
            db $08, $AF
            db $08, $D8
        db   2              ; Spans @ $3Axx
            db $20, $57
            db $20, $D7
        db   1              ; Spans @ $3Bxx
            db $20, $C7
        db   2              ; Spans @ $3Cxx
            db $08, $6F
            db $08, $D8
        db   2              ; Spans @ $3Dxx
            db $08, $AF
            db $09, $D8
        db   2              ; Spans @ $3Exx
            db $20, $57
            db $08, $D7
        db   1              ; Spans @ $3Fxx
            db $20, $C7
; === Main ===
        db   2 + $80        ; Spans @ $20xx
            db $4C, $6F
            db $44, $EF
        db   2              ; Spans @ $21xx
            db $7E, $57
            db $44, $AF
        db   2              ; Spans @ $22xx
            db $44, $2F
            db $44, $D7
        db   2              ; Spans @ $23xx
            db $46, $57
            db $04, $C7
        db   3              ; Spans @ $24xx
            db $4C, $6F
            db $40, $D7
            db $44, $EF
        db   3              ; Spans @ $25xx
            db $6E, $57
            db $44, $AF
            db $40, $D7
        db   2              ; Spans @ $26xx
            db $44, $2F
            db $46, $D7
        db   2              ; Spans @ $27xx
            db $44, $57
            db $04, $C7
        db   2              ; Spans @ $28xx
            db $4C, $6F
            db $40, $D7
        db   3              ; Spans @ $29xx
            db $44, $57
            db $44, $AF
            db $40, $D7
        db   2              ; Spans @ $2Axx
            db $4D, $2F
            db $6F, $D7
        db   2              ; Spans @ $2Bxx
            db $47, $57
            db $04, $C7
        db   2              ; Spans @ $2Cxx
            db $4E, $6F
            db $40, $D7
        db   2              ; Spans @ $2Dxx
            db $44, $AF
            db $40, $D7
        db   2              ; Spans @ $2Exx
            db $4E, $2F
            db $44, $D7
        db   2              ; Spans @ $2Fxx
            db $04, $47
            db $44, $C7
        db   2              ; Spans @ $30xx
            db $4F, $6F
            db $40, $D7
        db   3              ; Spans @ $31xx
            db $04, $2F
            db $44, $AF
            db $44, $D7
        db   3              ; Spans @ $32xx
            db $4C, $2F
            db $44, $57
            db $42, $D7
        db   2              ; Spans @ $33xx
            db $04, $47
            db $44, $C7
        db   2              ; Spans @ $34xx
            db $5F, $6F
            db $44, $D7
        db   3              ; Spans @ $35xx
            db $04, $2F
            db $44, $AF
            db $44, $D7
        db   3              ; Spans @ $36xx
            db $44, $2F
            db $44, $57
            db $44, $D7
        db   2              ; Spans @ $37xx
            db $04, $47
            db $44, $C7
        db   2              ; Spans @ $38xx
            db $4E, $6F
            db $44, $D7
        db   3              ; Spans @ $39xx
            db $04, $2F
            db $44, $AF
            db $44, $D7
        db   3              ; Spans @ $3Axx
            db $44, $2F
            db $44, $57
            db $44, $D7
        db   2              ; Spans @ $3Bxx
            db $04, $47
            db $44, $C7
        db   2              ; Spans @ $3Cxx
            db $4C, $6F
            db $44, $D7
        db   3              ; Spans @ $3Dxx
            db $44, $2F
            db $44, $AF
            db $68, $D7
        db   2              ; Spans @ $3Exx
            db $44, $57
            db $44, $D7
        db   2              ; Spans @ $3Fxx
            db $04, $47
            db $4C, $C7
        db 0
; Total Bytes Aux.: $0089 (137)
; Total Bytes Main: $00B4 (180)
; Total Bytes Misc: $0002 (2)
;================== $013F (319)
