; --- NOTE ---
; This (data) sprite file was AUTO GENERATED by frame_delta
; ../TITLELOGO.DHGR ../TITLE02.DHGR 2 -data
;
; === Aux ===
        db $40              ; Base Address
        db   3              ; Spans @ $40xx
            db $00, $2E
            db $22, $AF
            db $20, $EF
        db   4              ; Spans @ $41xx
            db $00, $47
            db $62, $6F
            db $22, $C7
            db $60, $EF
        db   2              ; Spans @ $42xx
            db $08, $58
            db $20, $AF
        db   1              ; Spans @ $43xx
            db $20, $2F
        db   4              ; Spans @ $44xx
            db $00, $2E
            db $26, $AF
            db $5C, $C8
            db $20, $EF
        db   3              ; Spans @ $45xx
            db $00, $47
            db $62, $6F
            db $22, $C7
        db   2              ; Spans @ $46xx
            db $08, $58
            db $20, $AF
        db   1              ; Spans @ $47xx
            db $20, $2F
        db   4              ; Spans @ $48xx
            db $00, $2E
            db $66, $AF
            db $00, $C8
            db $20, $EF
        db   3              ; Spans @ $49xx
            db $00, $47
            db $62, $6F
            db $62, $C7
        db   3              ; Spans @ $4Axx
            db $00, $30
            db $08, $58
            db $60, $AF
        db   0 + $C0        ; SKIP  @ $4Bxx
        db   4              ; Spans @ $4Cxx
            db $23, $2F
            db $70, $AF
            db $00, $C8
            db $20, $EF
        db   3              ; Spans @ $4Dxx
            db $00, $48
            db $62, $6F
            db $62, $C7
        db   1              ; Spans @ $4Exx
            db $60, $AF
        db   0 + $C0        ; SKIP  @ $4Fxx
        db   4              ; Spans @ $50xx
            db $00, $2E
            db $20, $AF
            db $00, $C8
            db $20, $EF
        db   2              ; Spans @ $51xx
            db $62, $6F
            db $62, $C7
        db   1              ; Spans @ $52xx
            db $60, $AF
        db   0 + $C0        ; SKIP  @ $53xx
        db   3              ; Spans @ $54xx
            db $00, $2E
            db $00, $C8
            db $20, $EF
        db   4              ; Spans @ $55xx
            db $20, $47
            db $74, $6F
            db $20, $C7
            db $08, $D8
        db   2              ; Spans @ $56xx
            db $60, $AF
            db $08, $D8
        db   1              ; Spans @ $57xx
            db $00, $86
        db   4              ; Spans @ $58xx
            db $53, $2F
            db $20, $6F
            db $00, $C8
            db $20, $EF
        db   4              ; Spans @ $59xx
            db $20, $47
            db $74, $6F
            db $20, $C7
            db $08, $D8
        db   2              ; Spans @ $5Axx
            db $60, $AF
            db $08, $D8
        db   1              ; Spans @ $5Bxx
            db $00, $86
        db   3              ; Spans @ $5Cxx
            db $20, $6F
            db $00, $C7
            db $60, $EF
        db   3              ; Spans @ $5Dxx
            db $20, $47
            db $60, $6F
            db $08, $D8
        db   3              ; Spans @ $5Exx
            db $08, $30
            db $60, $AF
            db $09, $D8
        db   1              ; Spans @ $5Fxx
            db $00, $86
; === Main ===
        db   3 + $80        ; Spans @ $40xx
            db $10, $AE
            db $13, $C8
            db $04, $EF
        db   4              ; Spans @ $41xx
            db $40, $47
            db $4C, $6F
            db $4C, $C7
            db $4E, $EF
        db   3              ; Spans @ $42xx
            db $04, $2F
            db $44, $57
            db $44, $AF
        db   1              ; Spans @ $43xx
            db $4C, $2F
        db   4              ; Spans @ $44xx
            db $04, $6F
            db $44, $AF
            db $01, $C8
            db $44, $EF
        db   3              ; Spans @ $45xx
            db $40, $47
            db $4E, $6F
            db $4C, $C7
        db   3              ; Spans @ $46xx
            db $04, $2F
            db $7E, $57
            db $44, $AF
        db   1              ; Spans @ $47xx
            db $44, $2F
        db   4              ; Spans @ $48xx
            db $04, $6F
            db $44, $AF
            db $01, $C8
            db $44, $EF
        db   4              ; Spans @ $49xx
            db $44, $47
            db $4C, $6F
            db $4C, $C7
            db $40, $D7
        db   3              ; Spans @ $4Axx
            db $04, $2F
            db $6E, $57
            db $44, $AF
        db   1              ; Spans @ $4Bxx
            db $44, $2F
        db   4              ; Spans @ $4Cxx
            db $19, $2E
            db $04, $6F
            db $04, $AF
            db $44, $EF
        db   4              ; Spans @ $4Dxx
            db $44, $47
            db $4C, $6F
            db $4C, $C7
            db $40, $D7
        db   3              ; Spans @ $4Exx
            db $44, $2F
            db $44, $57
            db $44, $AF
        db   0 + $C0        ; SKIP  @ $4Fxx
        db   4              ; Spans @ $50xx
            db $04, $6F
            db $04, $AF
            db $00, $C7
            db $44, $EF
        db   4              ; Spans @ $51xx
            db $44, $47
            db $4C, $6F
            db $4E, $C7
            db $40, $D7
        db   2              ; Spans @ $52xx
            db $44, $2F
            db $44, $AF
        db   0 + $C0        ; SKIP  @ $53xx
        db   4              ; Spans @ $54xx
            db $04, $2F
            db $04, $6F
            db $00, $C7
            db $4C, $EF
        db   3              ; Spans @ $55xx
            db $4C, $6F
            db $4E, $C7
            db $40, $D7
        db   3              ; Spans @ $56xx
            db $44, $2F
            db $44, $AF
            db $58, $D7
        db   0 + $C0        ; SKIP  @ $57xx
        db   5              ; Spans @ $58xx
            db $11, $2E
            db $11, $48
            db $04, $6F
            db $00, $C7
            db $4C, $EF
        db   4              ; Spans @ $59xx
            db $44, $47
            db $4E, $6F
            db $5E, $C7
            db $40, $D7
        db   3              ; Spans @ $5Axx
            db $44, $2F
            db $4D, $AF
            db $4C, $D7
        db   0 + $C0        ; SKIP  @ $5Bxx
        db   5              ; Spans @ $5Cxx
            db $10, $2E
            db $11, $48
            db $04, $6F
            db $00, $C7
            db $4C, $EF
        db   4              ; Spans @ $5Dxx
            db $4C, $47
            db $56, $6F
            db $44, $C7
            db $44, $D7
        db   3              ; Spans @ $5Exx
            db $44, $2F
            db $4E, $AF
            db $68, $D7
        db   1              ; Spans @ $5Fxx
            db $10, $86
        db 0
; Total Bytes Aux.: $00B5 (181)
; Total Bytes Main: $00D0 (208)
; Total Bytes Misc: $0002 (2)
;================== $0187 (391)
